dist: trusty
sudo: require
language: cpp
compiler: gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-6
            - g++-6
            - cmake
script:
    # Link gcc and g++ to their version 6 releases
    - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
    - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
    # Export CC and CXX to tell CMake which compiler to use
    - export CC=/usr/bin/gcc-6
    - export CXX=/usr/bin/g++-6
    # Check versions of gcc, g++, and cmake
    - gcc -v && g++ -v && cmake --version
    # The build commands
    - make tests

